class Const:
    LEFT_EYE = "left_eye"
    RIGHT_EYE = "right_eye"
    MOUTH = "mouth"
    
    EASING_TO_INT_MAP = {
        "LinearInOut": 0,
        "QuadEaseInOut": 1,
        "QuadEaseIn": 2,
        "QuadEaseOut": 3,
        "CubicEaseIn": 4,
        "CubicEaseOut": 5,
        "CubicEaseInOut": 6,
        "QuarticEaseIn": 7,
        "QuarticEaseOut": 8,
        "QuarticEaseInOut": 9,
        "QuinticEaseIn": 10,
        "QuinticEaseOut": 11,
        "QuinticEaseInOut": 12,
        "SineEaseIn": 13,
        "SineEaseOut": 14,
        "SineEaseInOut": 15,
        "CircularEaseIn": 16,
        "CircularEaseOut": 17,
        "CircularEaseInOut": 18,
        "ExponentialEaseIn": 19,
        "ExponentialEaseOut": 20,
        "ExponentialEaseInOut": 21,
        "ElasticEaseIn": 22,
        "ElasticEaseOut": 23,
        "ElasticEaseInOut": 24,
        "BackEaseIn": 25,
        "BackEaseOut": 26,
        "BackEaseInOut": 27,
        "BounceEaseIn": 28,
        "BounceEaseOut": 29,
        "BounceEaseInOut": 30,
    }
    
    INT_TO_EASING_MAP = {
        0: "LinearInOut",
        1: "QuadEaseInOut",
        2: "QuadEaseIn",
        3: "QuadEaseOut",
        4: "CubicEaseIn",
        5: "CubicEaseOut",
        6: "CubicEaseInOut",
        7: "QuarticEaseIn",
        8: "QuarticEaseOut",
        9: "QuarticEaseInOut",
        10: "QuinticEaseIn",
        11: "QuinticEaseOut",
        12: "QuinticEaseInOut",
        13: "SineEaseIn",
        14: "SineEaseOut",
        15: "SineEaseInOut",
        16: "CircularEaseIn",
        17: "CircularEaseOut",
        18: "CircularEaseInOut",
        19: "ExponentialEaseIn",
        20: "ExponentialEaseOut",
        21: "ExponentialEaseInOut",
        22: "ElasticEaseIn",
        23: "ElasticEaseOut",
        24: "ElasticEaseInOut",
        25: "BackEaseIn",
        26: "BackEaseOut",
        27: "BackEaseInOut",
        28: "BounceEaseIn",
        29: "BounceEaseOut",
        30: "BounceEaseInOut",
    }
